# inherit from the proprietary version
-include vendor/lge/f6mt/BoardConfigVendor.mk

# Include path
# LGE will hopefully get a newer kernel out one day, but till then to get msm video and audio going we need this
TARGET_SPECIFIC_HEADER_PATH := device/lge/f6mt/include

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := msm8960
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := krait
TARGET_CPU_SMP := true
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true

# NFC
BOARD_HAVE_NFC := true
BOARD_NFC_HAL_SUFFIX := msm8960

TARGET_BOOTLOADER_NAME := f6

TARGET_PRODUCT := f6

#selinux permissive to try to get twrp booting
BOARD_KERNEL_CMDLINE := androidboot.hardware=f6mt user_debug=31 vmalloc=308M selinux=permissive
BOARD_KERNEL_BASE := 0x80200000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x02000000

#TARGET_PREBUILT_KERNEL := device/lge/f6mt/kernel
#LOCAL_KERNEL := $(TARGET_PREBUILT_KERNEL)

TARGET_KERNEL_CONFIG := f6_mpcs_tmo_defconfig

# Krait optimizations
TARGET_USE_KRAIT_BIONIC_OPTIMIZATION := true
TARGET_USE_KRAIT_PLD_SET := true
TARGET_KRAIT_BIONIC_PLDOFFS := 10
TARGET_KRAIT_BIONIC_PLDTHRESH := 10
TARGET_KRAIT_BIONIC_BBTHRESH := 64
TARGET_KRAIT_BIONIC_PLDSIZE := 64


# QCOM
BOARD_USES_QCOM_HARDWARE := true
TARGET_USES_QCOM_BSP := true
COMMON_GLOBAL_CFLAGS += -DQCOM_HARDWARE -DQCOM_BSP

# QCOM enhanced A/V
TARGET_ENABLE_QC_AV_ENHANCEMENTS := true

# Use CAF media driver variant for 8960
TARGET_QCOM_MEDIA_VARIANT := caf

# Use retire fence from MDP driver
TARGET_DISPLAY_USE_RETIRE_FENCE := true

BOARD_EGL_CFG := device/lge/f6mt/prebuilt/lib/egl/egl.cfg

# Filesystem
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 50331648
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 50331648
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 5167382528
BOARD_USERDATAIMAGE_PARTITION_SIZE := 5536481280
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_VOLD_MAX_PARTITIONS := 97

# Recovery
RECOVERY_FSTAB_VERSION = 2
TARGET_RECOVERY_FSTAB := device/lge/f6mt/recovery/fstab.qcom
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_15x24.h\"
ENABLE_LOKI_RECOVERY := true
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_RECOVERY_SWIPE := false
BOARD_USES_MMCUTILS := true
BOARD_HAS_LARGE_FILESYSTEM := true
AM_CONNOR := true
#BOARD_HAS_NO_MISC_PARTITION := true
TARGET_RECOVERY_LCD_BACKLIGHT_PATH := \"/sys/devices/platform/msm_fb.525569/leds/lcd-backlight/brightness\"

# TWRP is not working yet
DEVICE_RESOLUTION := 540x960
RECOVERY_SDCARD_ON_DATA := true
TW_INTERNAL_STORAGE_PATH := "/data/media"
TW_INTERNAL_STORAGE_MOUNT_POINT := "data"
TW_EXTERNAL_STORAGE_PATH := "/sdcard"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "sdcard"

TW_BRIGHTNESS_PATH := "/sys/devices/platform/msm_fb.525569/leds/lcd-backlight/brightness"

TW_NO_REBOOT_BOOTLOADER := true 
TW_NO_USB_STORAGE := true
TW_DEFAULT_EXTERNAL_STORAGE := true







